### ISSUE TITLE
Possible Seed bug when ran with flush?

### ISSUE THREAD

**Issue by MACscr** [bastinald/ui#4]
It appears that when running `ui:migrate --fs` everything appears to run and i get success messages for both, but then looking at the tables, the seeds never run. It isn't until i run the `--s` on its own where it finally spits out an error. Guess it doesn't like enum types, but thats a whole other matter and maybe i will just not use them.

**Comment by bastinald** [comment]
That's weird because if you look at the code for the command, it runs the seeders the exact same way with `--s` and `--fs`.

What is the error you're getting so I can reproduce it?

**Comment by MACscr** [comment]
It didnt like my enum fields. I removed them all (reluctantly) and changed them all to basic strings, but here is the error before changed it:

```
[2021-05-22 00:30:54] local.ERROR: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it. {"exception":"[object] (Doctrine\\DBAL\\Exception(code: 0): Unknown database type enum requested, Doctrine\\DBAL\\Platforms\\MySQL57Platform may not support it. at /Users/macscr/sites/vanilla/vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:398)
[stacktrace]
#0 /Users/macscr/sites/vanilla/vendor/doctrine/dbal/src/Schema/MySQLSchemaManager.php(135): Doctrine\\DBAL\\Platforms\\AbstractPlatform->getDoctrineTypeMapping('enum')
#1 /Users/macscr/sites/vanilla/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(884): Doctrine\\DBAL\\Schema\\MySQLSchemaManager->_getPortableTableColumnDefinition(Array)
#2 /Users/macscr/sites/vanilla/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(195): Doctrine\\DBAL\\Schema\\AbstractSchemaManager->_getPortableTableColumnList('events', 'vanilla', Array)
#3 /Users/macscr/sites/vanilla/vendor/doctrine/dbal/src/Schema/AbstractSchemaManager.php(308): Doctrine\\DBAL\\Schema\\AbstractSchemaManager->listTableColumns('events')
#4 /Users/macscr/sites/vanilla/vendor/doctrine/dbal/src/Schema/MySQLSchemaManager.php(334): Doctrine\\DBAL\\Schema\\AbstractSchemaManager->listTableDetails('events')
#5 /Users/macscr/sites/vanilla/vendor/bastinald/ui/src/Commands/MigrateCommand.php(72): Doctrine\\DBAL\\Schema\\MySQLSchemaManager->listTableDetails('events')
#6 /Users/macscr/sites/vanilla/vendor/bastinald/ui/src/Commands/MigrateCommand.php(51): Bastinald\\UI\\Commands\\MigrateCommand->migrate(Object(App\\Models\\Event))
#7 /Users/macscr/sites/vanilla/vendor/bastinald/ui/src/Commands/MigrateCommand.php(20): Bastinald\\UI\\Commands\\MigrateCommand->handleAutomaticMigrations()
#8 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Bastinald\\UI\\Commands\\MigrateCommand->handle()
#9 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#11 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#14 /Users/macscr/sites/vanilla/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /Users/macscr/sites/vanilla/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /Users/macscr/sites/vanilla/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(Bastinald\\UI\\Commands\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /Users/macscr/sites/vanilla/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /Users/macscr/sites/vanilla/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /Users/macscr/sites/vanilla/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"}
```

Now even after resolving the error, nothing appears to seed when i run `php artisan ui:migrate --s` besides the basic default test user that is located in DatabaseSeeder.php. No errors and actually states even if i only use the seed flag: 

```
Migration complete!
Seeding complete!
```

**Comment by bastinald** [comment]
Can you paste the Model class causing this and your DatabaseSeeder code?

Also, I recommend using string columns over enums because enums are a pain in the ass to change later.

**Comment by MACscr** [comment]
```
<?php

namespace App\Models;

use Bastinald\UI\Traits\HasFillable;
use Faker\Generator;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Schema\Blueprint;

class Event extends Model
{
    use HasFactory;
    use HasFillable;

    public function migration(Blueprint $table)
    {
        $table->id();
        $table->string('name');
        $table->dateTime('start');
        $table->dateTime('end');
        //$table->enum('event_type', ['farmers_market', 'family']);
        $table->string('event_type');
        $table->longText('description');
        $table->longText('registration_url');
        $table->timestamp('created_at')->nullable();
        $table->timestamp('updated_at')->nullable();
    }

    public function definition(Generator $faker)
    {
        return [
            'name' => $faker->name,
            'start' => $faker->dateTime(),
            'end' => $faker->dateTime(),
            'event_type' => $faker->randomElement(['farmers_market', 'family']),
            'description' => $faker->text,
            'registration_url' => $faker->text,
        ];
    }
}
```

**Comment by bastinald** [comment]
Please post your `DatabaseSeeder` code

**Comment by MACscr** [comment]
Ah, now I am feeling a bit dumb here as I have nothing in it besides the original test user which i commented out. Guessing im supposed to call the factories in the main db file? I typically created individual factory files like so: 

```
cat database/seeders/EventSeeder.php 
<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Event::factory()->count(5)->create();
    }
}
```
and thought your system was doing some magic behind the scenes like migrations, so i didnt do anything in this particular install. I wonder why i was getting that enum error then only on running the seed command when i didnt actually have that event factory setup to be called as I should have. Hopefully I am making some sense.

**Comment by bastinald** [comment]
You gotta use the factories as you normally would in your `DatabaseSeeder` :)

The package doesn't do that for you, because you need to define how many fake things you wanna make, and often times you need to specify the seeders to run in a specific order.

**Comment by MACscr** [comment]
Yep, makes perfect sense as i typed out that previous message. Though, still was odd about the errors. Shows how new i am to laravel. Doh. Thanks!
